version: '3.9'
services:
  crud_db:
    container_name: evolumais_db
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_NAME: ${DATA_NAME}
    volumes:
      - .docker/dbdata:var/lib/postgresql/data
  app:
    build: .
    container_name: 'api-evolumais'
    command: sh -c "npm run start:dev"
    ports:
      - 4002:4002
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_NAME: ${DATA_NAME}

    volumes:
      - .:/usr/app
    links:
      - evolumais_db
    depends_on:
      - evolumais_db
